name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Compilar aplicação web
        run: |
          npm install
          npm run build

      - name: Implantação no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
